### ISSUE TITLE
your website is gar bage`\\\\

### ISSUE THREAD

**Issue by VenkatsaiCSP** [Sanjit1/Sanjit1.github.io#1]
THE DESI GAME IS  VERY BAD IMPOSSSIBLE TO BEAT

**Comment by Sanjit1** [comment]
Thats the Point!

DESI PEOPLE ARE BEASTS.
YOU CANNOT BEAT THEM


[![best-regards](https://img.shields.io/badge/Best%20regards-Sanjit-accff2?style=for-the-badge)](https://www.sanjit.wtf)
